/*  fcrtBare.c - The simplest kernel module.

* Copyright (C) 2013 - 2016 Xilinx, Inc
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>
#include <linux/uaccess.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>


#include "fcrt_define.h"

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("fcrtBare - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "fcrtBare"
	
static struct device * dev;

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

struct fcrtBare_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

//////////// fcrtBaremetal///////////////////////////////////
#define Q_LEN	    4
#define MSG_MAX_LEN 8
static FCRT_RX_DESC * rx_dsc=NULL;
static u32 rx_cnt;

FCRT_TX_DESC * tx_dsc=NULL;
static u32 tx_cnt;

static u8 ** tx_q=NULL;
static u32 * tx_m_len;
static u32 tx_m_cnt, tx_m_w_ind, tx_m_r_ind;
static u8 ** rx_q=NULL;
static u32 * rx_m_len;
static u32 rx_m_cnt, rx_m_w_ind, rx_m_r_ind;

static fcrt_allocator fcrt_alloc = NULL;
static fcrt_release fcrt_free = NULL;

static void fcrtRelease(void);
static int loop_msg(void);

int fcrtInit(FCRT_INIT_PARAMS * param)
{
	u32 i =0;
    dev_err(dev, "[%s]", __func__);
    fcrt_alloc = param->fcrt_alloc;
	fcrt_free = param->fcrt_free;
    tx_cnt = param->nTx;
    rx_cnt = param->nRx;
	dev = param->dev;
	dma_addr_t no_use;
    // tx_dsc = kzalloc(tx_cnt * sizeof(FCRT_TX_DESC), GFP_KERNEL);
    // rx_dsc = kzalloc(rx_cnt * sizeof(FCRT_RX_DESC), GFP_KERNEL);
    if (tx_q == NULL)
    {
		tx_m_cnt = 0;
		tx_m_w_ind = 0;
		tx_m_r_ind = 0;
#if 1
		dev_err(dev,"\ntx_q alloc");
#endif
		tx_q = (u8**)fcrt_alloc(sizeof(u8*), Q_LEN * sizeof(u8*), &no_use);
		if(tx_q == NULL)
		{
			dev_err(dev,"[%s]cant alloc mem for tx_q", __func__);
			return -ENOMEM;
		}
		tx_m_len = (u32*)fcrt_alloc(sizeof(u32), Q_LEN * sizeof(u32), &no_use);
		if(tx_m_len == NULL)
		{
			dev_err(dev,"[%s]cant alloc mem for tx_m_len buf", __func__);
			return -ENOMEM;
		}
#if 1
		dev_err(dev,"\ntx_q filling");
#endif
		for(i = 0; i < Q_LEN; i++)
		{
			tx_q[i] = fcrt_alloc(sizeof(u8), MSG_MAX_LEN, &no_use);
			if(tx_q[i] == NULL)
			{
				dev_err(dev,"[%s]cant alloc mem for tx_q[%d]", __func__, i);
				return -ENOMEM;
			}
			tx_m_len[i] = 0;
		}
#if 1
		dev_err(dev,"\ntx_q show");
		for(i = 0; i < Q_LEN; i++)
		{
			dev_err(dev,"tx_q[%d]: %p", i, tx_q[i]);
		}
#endif
    }
	
    if (rx_q == NULL)
    {
		rx_m_cnt = 0;
		rx_m_w_ind = 0;
		rx_m_r_ind = 0;
#if 1
		dev_err(dev,"\nrx_q alloc");
#endif
		rx_q = (u8**)fcrt_alloc(sizeof(u8*), Q_LEN * sizeof(u8*), &no_use);
		if(rx_q == NULL)
		{
			dev_err(dev,"[%s]cant alloc mem for rx_q", __func__);
			return -ENOMEM;
		}
		rx_m_len = (u32*)fcrt_alloc(sizeof(u32), Q_LEN * sizeof(u32), &no_use);
		if(rx_m_len == NULL)
		{
			dev_err(dev,"[%s]cant alloc mem for tx_m_len buf", __func__);
			return -ENOMEM;
		}
#if 1
		dev_err(dev,"\nrx_q filling");
#endif
		for(i = 0; i < Q_LEN; i++)
		{
			rx_q[i] = fcrt_alloc(sizeof(u8), MSG_MAX_LEN, &no_use);
			if(rx_q[i] == NULL)
			{
				dev_err(dev,"[%s]cant alloc mem for rx_q[%d]", __func__, i);
				return -ENOMEM;
			}
			rx_m_len[i] = 0;
		}
#if 1
		dev_err(dev,"\nrx_q show");
		for(i = 0; i < Q_LEN; i++)
		{
			dev_err(dev,"rx_q[%d]: %p", i, rx_q[i]);
		}
#endif
    }
    return 0;
}
EXPORT_SYMBOL(fcrtInit);


int fcrtSend(unsigned int vc, void* buf, unsigned int size)
{
	dev_err(dev, "[%s]", __func__);
	if(tx_m_cnt == Q_LEN)
	{
		dev_err(dev,"[%s]tx_msg_queue is full", __func__);
		return -EAGAIN;
	}
	if(size > MSG_MAX_LEN)
	{
		dev_err(dev,"[%s]Max msg len is: %d", __func__, MSG_MAX_LEN);
		return -EINVAL;
	}
	if(copy_from_user(tx_q[tx_m_w_ind], buf, size)!=0)
	{
		dev_err(dev, "[%s]copy from user fails", __func__);
		return -EAGAIN;
	}
	tx_m_len[tx_m_w_ind] = size;
	tx_m_w_ind++;
	if(tx_m_w_ind == Q_LEN)
	{
		tx_m_w_ind = 0;
	}
	tx_m_cnt++;
#if 0
	print_hex_dump(KERN_ALERT, "fcrtSend: ", DUMP_PREFIX_ADDRESS, 32, 1, rx_q, size, true);
#endif

#if 1
	loop_msg();
#endif

	return 0;
}
EXPORT_SYMBOL(fcrtSend);

int fcrtChk(unsigned int vc)
{
	if(rx_m_len > 0)
		return 0;
	else
		return -EAGAIN;
}
EXPORT_SYMBOL(fcrtChk);

int fcrtRecv(unsigned int vc, void* buf, unsigned int * size)
{
	dev_err(dev, "[%s]", __func__);
	if(rx_m_cnt == 0)
	{
		dev_err(dev,"[%s]rcv queue is empty", __func__);
		return -EAGAIN;
	}
	if(copy_to_user(buf, rx_q[rx_m_r_ind], rx_m_len[rx_m_r_ind]) != 0)
	{
		dev_err(dev, "[%s]copy to user fails", __func__);
		return -EAGAIN;
	}
	rx_m_cnt--;
    *size = rx_m_len[rx_m_r_ind];

	rx_m_r_ind++;
	if(rx_m_r_ind == Q_LEN)
	{
		rx_m_r_ind = 0;
	}
#if 1
    print_hex_dump(KERN_ALERT, "fcrtRecv: ", DUMP_PREFIX_ADDRESS, 32, 1, buf, *size,
                   true);
#endif
	return 0;
}
EXPORT_SYMBOL(fcrtRecv);


static void fcrtRelease(void)
{
	dev_err(dev,"[%s]", __func__);
	if(tx_q != NULL)
	{
		fcrt_free(tx_q);
		tx_q = NULL;
	}
	if(rx_q != NULL)
	{
		fcrt_free(rx_q);
		rx_q = NULL;
	}
	if(rx_dsc != NULL)
	{
		fcrt_free(rx_dsc);
		rx_dsc = NULL;
	}
	if(tx_dsc != NULL)
	{
		fcrt_free(tx_dsc);
		tx_dsc = NULL;
	}
}
///копируем сообщение из очереди передачи в очередь приема
static int loop_msg(void)
{
	if(tx_m_cnt == 0)
	{
		dev_err(dev,"[%s]tx msg queue is empty", __func__);
		return -EAGAIN;
	}
	tx_m_cnt--;
	if(rx_m_cnt < Q_LEN)
	{
		rx_m_cnt++;
	}
	else
	{
		dev_warn(dev, "[%s]RcvQueue is full. Overwrite most old received message", __func__);
	}

	memcpy(rx_q[rx_m_w_ind], tx_q[tx_m_r_ind], tx_m_len[tx_m_r_ind]);
	rx_m_len[rx_m_w_ind] = tx_m_len[tx_m_r_ind];
	rx_m_w_ind++;
	if(rx_m_w_ind == Q_LEN)
		rx_m_w_ind = 0;

	tx_m_r_ind++;
	if(tx_m_r_ind == Q_LEN)
		tx_m_r_ind = 0;
	
	return 0;
}
///////////////////////////////////////

static irqreturn_t fcrtBare_irq(int irq, void *lp)
{
	dev_err(dev, "fcrtBare interrupt\n");
	return IRQ_HANDLED;
}

static int fcrtBare_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct fcrtBare_local *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct fcrtBare_local *) kmalloc(sizeof(struct fcrtBare_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate fcrtBare device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "fcrtBare: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "fcrtBare at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	rc = request_irq(lp->irq, &fcrtBare_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	dev_info(dev,"fcrtBare at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int fcrtBare_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct fcrtBare_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id fcrtBare_of_match[] = {
	{ .compatible = "vendor,fcrtBare", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, fcrtBare_of_match);
#else
# define fcrtBare_of_match
#endif


static struct platform_driver fcrtBare_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= fcrtBare_of_match,
	},
	// .probe		= fcrtBare_probe,
	// .remove		= fcrtBare_remove,
};

static int __init fcrtBare_init(void)
{
	dev_err(dev, "<1>FCRT Bare Module. Hello module world.\n");
	// dev_err("<1>FCRT Bare Module parameters were (0x%08x) and \"%s\"\n", myint,
	    //    mystr);

	// return platform_driver_register(&fcrtBare_driver);
	return 0;
}


static void __exit fcrtBare_exit(void)
{
	// platform_driver_unregister(&fcrtBare_driver);
	dev_err(dev, "FCRT Bare. Goodbye module world.\n");
}

module_init(fcrtBare_init);
module_exit(fcrtBare_exit);
