/*  fcrtBare.c - The simplest kernel module.

* Copyright (C) 2013 - 2016 Xilinx, Inc
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>
#include <linux/uaccess.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>


#include "fcrt_define.h"

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("fcrtBare - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "fcrtBare"
	
static struct device * dev;

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

struct fcrtBare_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

struct fcrtRxQueue
{
	u32 asm_id;
	u32 q_len;
	u32 max_m_len;
	u8 ** rx_q;
	u32 * rx_m_len;
	u32 rx_m_cnt;
	u32 rx_m_w_ind;
	u32 rx_m_r_ind;
};

//////////// fcrtBaremetal///////////////////////////////////
static FCRT_RX_DESC * rx_dsc=NULL;
static FCRT_TX_DESC * tx_dsc=NULL;
static int vc_cnt;

///одна очередь для сообщений всех каналов
static u8 ** tx_q=NULL;//message addr
static u32 * tx_m_len;//msg len
static u32 * tx_m_vc;//msg vc
static u32 tx_m_cnt, tx_m_w_ind, tx_m_r_ind;

static struct fcrtRxQueue * rx_q;

static fcrt_allocator fcrt_alloc = NULL;
static fcrt_release fcrt_free = NULL;

static void fcrtRelease(void);
static int loop_msg(void);

static void show_rxq_elem(struct fcrtRxQueue * ptr)
{
	int j;
	printk(KERN_ALERT"Base ptr: %p", ptr);
	printk(KERN_ALERT "asm_id: 0x%x; q_depth: %d; msg_max_len: %d", ptr->asm_id, ptr->q_len, ptr->max_m_len);
	printk(KERN_ALERT "queue addr");
	for (j = 0; j < ptr->q_len; j++)
	{
		printk(KERN_ALERT "[%d]:v.addr: %p; m_len: %d", j, ptr->rx_q[j], ptr->rx_m_len[j]);
	}
}

static void show_rx_queue(struct fcrtRxQueue * rxq, u32 nVC)
{
	u32 i;
	struct fcrtRxQueue * ptr = rxq;
	for(i = 0; i < nVC; i++)
	{
		printk(KERN_ALERT"------rx queue[%d]-----", i);
		show_rxq_elem(&rxq[i]);
	}
}

static int setup_rx_queue(FCRT_RX_DESC * rxd, struct fcrtRxQueue * rxq)
{
	u32 i;
	dma_addr_t no_use;
    if (rxq->rx_q != NULL)
    {
        printk(KERN_ALERT "[%s]VC[%d]rx_q is not NULL", __func__, rxq->asm_id);
    }
	rxq->rx_m_cnt = 0;
	rxq->rx_m_w_ind = 0;
	rxq->rx_m_r_ind = 0;
	rxq->q_len = rxd->q_depth;
	rxq->asm_id = rxd->asm_id;
	rxq->max_m_len = rxd->max_size;

    rxq->rx_q = (u8 **)fcrt_alloc(rxq->q_len * sizeof(u8 *), sizeof(u8 *), &no_use);
    if (rxq->rx_q == NULL)
    {
        printk(KERN_INFO "[%s]cant alloc mem for rx_q", __func__);
        return -ENOMEM;
    }
    rxq->rx_m_len = (u32 *)fcrt_alloc(rxq->q_len * sizeof(u32), sizeof(u32), &no_use);
    if (rxq->rx_m_len == NULL)
    {
        printk(KERN_INFO "[%s]cant alloc mem for tx_m_len buf", __func__);
        return -ENOMEM;
    }
#if 0
    printk(KERN_ALERT"rx_q filling");
#endif
    for (i = 0; i < rxq->q_len; i++)
    {
        rxq->rx_q[i] = fcrt_alloc(rxq->max_m_len, sizeof(u8), &no_use);
        if (rxq->rx_q[i] == NULL)
        {
            printk(KERN_INFO "[%s]cant alloc mem for vc[%d]rx_q", __func__, rxq->asm_id);
            return -ENOMEM;
        }
        rxq->rx_m_len[i] = 0;
    }
#if 0
    printk(KERN_INFO "\nrx_q show");
    for (i = 0; i < rxq->q_len; i++)
    {
        printk(KERN_INFO "rx_q[%d]: %p", i, rxq->rx_q[i]);
    }
#endif
}

//
//выделяет память для очереди исходящих сообщений
static int setup_tx_queue(void)
{
    dma_addr_t no_use;
	u32 i;
	if (tx_q != NULL)
    {
        printk(KERN_ALERT "[%s]tx_q is not NULL", __func__);
    }
    tx_m_cnt = 0;
    tx_m_w_ind = 0;
    tx_m_r_ind = 0;

#if 1
    printk(KERN_ALERT "\ntx_q alloc");
#endif
	tx_q = (u8 **)fcrt_alloc(TX_Q_LEN * sizeof(u8 *), sizeof(u8 *), &no_use);
	if (tx_q == NULL)
	{
		printk(KERN_ALERT "[%s]cant alloc mem for tx_q", __func__);
		return -ENOMEM;
	}
	tx_m_len = (u32 *)fcrt_alloc(TX_Q_LEN * sizeof(u32), sizeof(u32), &no_use);
	if (tx_m_len == NULL)
	{
		printk(KERN_ALERT "[%s]cant alloc mem for tx_m_len buf", __func__);
		return -ENOMEM;
	}
	tx_m_vc = (u32 *)fcrt_alloc(TX_Q_LEN * sizeof(u32), sizeof(u32), &no_use);
	if (tx_m_vc == NULL)
	{
		printk(KERN_ALERT "[%s]cant alloc mem for tx_m_vc buf", __func__);
		return -ENOMEM;
	}
#if 1
	printk(KERN_ALERT"tx_q filling");
#endif
	for (i = 0; i < TX_Q_LEN; i++)
	{
		tx_q[i] = fcrt_alloc(MSG_MAX_LEN, sizeof(u8), &no_use);
		if (tx_q[i] == NULL)
		{
			printk(KERN_ALERT "[%s]cant alloc mem for tx_q[%d]", __func__, i);
			return -ENOMEM;
		}
		tx_m_len[i] = 0;
	}
#if 1
    printk(KERN_INFO "\ntx_q show");
    for (i = 0; i < RX_Q_LEN; i++)
    {
        printk(KERN_INFO "tx_q[%d]: %p", i, tx_q[i]);
    }
#endif
	return 0;
}

#ifdef FCRT_INIT_LONG_PARAM
int fcrtInit(void* regs, FCRT_CTRL_CFG* ctrl, FCRT_TX_DESC* txCfg, FCRT_RX_DESC* rxCfg,
unsigned nVC, fcrt_allocator fcrtAlloc)
#else
int fcrtInit(FCRT_INIT_PARAMS * param)
#endif
{
    u32 i = 0;
	dma_addr_t no_use;
    printk(KERN_ALERT "[%s]", __func__);
#ifdef FCRT_INIT_LONG_PARAM
    fcrt_alloc = fcrtAlloc;
    vc_cnt = nVC;
#else
    fcrt_alloc = param->fcrt_alloc;
    vc_cnt = param->nVC;
    dev = param->dev;
#endif
    // tx_dsc = kzalloc(vc_cnt * sizeof(FCRT_TX_DESC), GFP_KERNEL);
    // rx_dsc = kzalloc(rx_cnt * sizeof(FCRT_RX_DESC), GFP_KERNEL);
    
	if(setup_tx_queue() != 0)
    {
		printk(KERN_ALERT"setup tx queue fails");
		return -ENOMEM;
	}

	rx_q = fcrt_alloc(vc_cnt * (sizeof(struct fcrtRxQueue)), sizeof(struct fcrtRxQueue), &no_use);
	if(rx_q == NULL)
	{
		printk(KERN_ALERT"could not alloc fcrtRxQueue memory");
		return -ENOMEM;
	}
	for(i = 0; i < vc_cnt; i++)
	{
		if(setup_rx_queue(&rxCfg[i], &rx_q[i]) != 0)
		{
			printk(KERN_ALERT"setup rx queue fails");
			return -ENOMEM;
		}
	}
#if 1
	show_rx_queue(rx_q, vc_cnt);
#endif
    return 0;
}
EXPORT_SYMBOL(fcrtInit);


int fcrtSend(unsigned int vc, void* buf, unsigned int size)
{
	printk(KERN_INFO"[%s]", __func__);
	if(tx_m_cnt == TX_Q_LEN)
	{
		printk(KERN_INFO"[%s]tx_msg_queue is full", __func__);
		return -EAGAIN;
	}
	if(size > MSG_MAX_LEN)
	{
		printk(KERN_INFO"[%s]Max msg len is: %d", __func__, MSG_MAX_LEN);
		return -EINVAL;
	}
	memcpy(tx_q[tx_m_w_ind], buf, size);
	tx_m_len[tx_m_w_ind] = size;
	tx_m_vc[tx_m_w_ind] = vc;
	tx_m_w_ind++;
	if(tx_m_w_ind == TX_Q_LEN)
	{
		tx_m_w_ind = 0;
	}
	tx_m_cnt++;
#if 1
	print_hex_dump(KERN_ALERT, "fcrtSend: ", DUMP_PREFIX_ADDRESS, 32, 1, rx_q, size, true);
#endif

	loop_msg();

	return 0;
}
EXPORT_SYMBOL(fcrtSend);

int fcrtRxReady(void)
{
	static int cur_ind = 0;
	int i = -1;
	if(rx_q == NULL)
		return -1;
	struct fcrtRxQueue * ptr = &rx_q[cur_ind];
    // dev_err(dev, "[%s]rx_m_len: %d", __func__, rx_m_len);
	if(ptr->rx_m_cnt > 0)
	{
		i = cur_ind;
		printk(KERN_INFO "[%s]vcd_ind: %d; msg_cnt: %d", __func__, i, ptr->rx_m_cnt);
	}
	cur_ind++;
	if(cur_ind == vc_cnt)
	{
		cur_ind = 0;
	}
	return i;
}
EXPORT_SYMBOL(fcrtRxReady);

int fcrtRecv(unsigned int vc, void* buf, unsigned int * size)
{
	struct fcrtRxQueue * ptr;
	u32 ri;
	printk(KERN_INFO"[%s]; buf: %p", __func__, buf);
	if(vc >= vc_cnt)
	{
		printk(KERN_ALERT"[%s]invalid vc ind: %d", __func__, vc);
		return -EINVAL;
	}
	if(rx_q[vc].rx_m_cnt == 0)
	{
		printk(KERN_INFO"[%s]rcv[%d] queue is empty", __func__, vc);
		return -EAGAIN;
	}
	ptr = &rx_q[vc];
	ri = ptr->rx_m_r_ind;
	memcpy(buf, ptr->rx_q[ri], ptr->rx_m_len[ri]);
    *size = ptr->rx_m_len[ri];
	ptr->rx_m_len[ri] = 0;

	ptr->rx_m_cnt--;
	ptr->rx_m_r_ind++;
	if(ptr->rx_m_r_ind == ptr->q_len)
	{
		ptr->rx_m_r_ind = 0;
	}
#if 1
    print_hex_dump(KERN_ALERT, "fcrtRecv: ", DUMP_PREFIX_ADDRESS, 32, 1, buf, *size,
                   true);
#endif
	return 0;
}
EXPORT_SYMBOL(fcrtRecv);

void fcrtShow(u32 param1, int param2, int param3)
{
	printk(KERN_ALERT"[%s]", __func__);
	return;
}
EXPORT_SYMBOL(fcrtShow);


static void fcrtRelease(void)
{
	printk(KERN_INFO"[%s]", __func__);
	if(tx_q != NULL)
	{
		fcrt_free(tx_q);
		tx_q = NULL;
	}
	if(rx_q != NULL)
	{
		fcrt_free(rx_q);
		rx_q = NULL;
	}
	if(rx_dsc != NULL)
	{
		fcrt_free(rx_dsc);
		rx_dsc = NULL;
	}
	if(tx_dsc != NULL)
	{
		fcrt_free(tx_dsc);
		tx_dsc = NULL;
	}
}
///копируем сообщение из очереди передачи в очередь приема
static int loop_msg(void)
{
	struct fcrtRxQueue * ptr;
	int res = -EAGAIN;
	if(tx_m_cnt == 0)
	{
		printk(KERN_INFO"[%s]tx msg queue is empty", __func__);
		return -EAGAIN;
	}
	u32 len = tx_m_len[tx_m_r_ind];
	u32 vcd_ind = tx_m_vc[tx_m_r_ind];
	ptr = &rx_q[vcd_ind];
	if(ptr->rx_m_cnt < ptr->q_len)
	{
		u32 w_ind = ptr->rx_m_w_ind;
		ptr->rx_m_cnt++;
		tx_m_cnt--;
		memcpy(ptr->rx_q[w_ind], tx_q[tx_m_r_ind], len);
		ptr->rx_m_len[w_ind] = len;
		tx_m_len[tx_m_r_ind] = 0;
		ptr->rx_m_w_ind++;
		if(ptr->rx_m_w_ind == ptr->q_len)
			ptr->rx_m_w_ind = 0;

		tx_m_r_ind++;
		if(tx_m_r_ind == TX_Q_LEN)
			tx_m_r_ind = 0;
		res = 0;
	}
	else
	{
		printk(KERN_INFO"[%s]RcvQueue is full", __func__);
	}

	return res;
}
///////////////////////////////////////

static irqreturn_t fcrtBare_irq(int irq, void *lp)
{
	printk(KERN_INFO"fcrtBare interrupt\n");
	return IRQ_HANDLED;
}

static int fcrtBare_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct fcrtBare_local *lp = NULL;

	int rc = 0;
	printk(KERN_INFO"Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		printk(KERN_INFO"invalid address\n");
		return -ENODEV;
	}
	lp = (struct fcrtBare_local *) kmalloc(sizeof(struct fcrtBare_local), GFP_KERNEL);
	if (!lp) {
		printk(KERN_INFO"Cound not allocate fcrtBare device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		printk(KERN_INFO"Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		printk(KERN_INFO"fcrtBare: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		printk(KERN_INFO"no IRQ found\n");
		printk(KERN_INFO"fcrtBare at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	rc = request_irq(lp->irq, &fcrtBare_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		printk(KERN_INFO"testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	printk(KERN_INFO"fcrtBare at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int fcrtBare_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct fcrtBare_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id fcrtBare_of_match[] = {
	{ .compatible = "vendor,fcrtBare", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, fcrtBare_of_match);
#else
# define fcrtBare_of_match
#endif


static struct platform_driver fcrtBare_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= fcrtBare_of_match,
	},
	// .probe		= fcrtBare_probe,
	// .remove		= fcrtBare_remove,
};

static int __init fcrtBare_init(void)
{
	printk(KERN_INFO"<1>FCRT Bare Module. Hello module world.\n");
	// dev_err("<1>FCRT Bare Module parameters were (0x%08x) and \"%s\"\n", myint,
	    //    mystr);

	// return platform_driver_register(&fcrtBare_driver);
	return 0;
}


static void __exit fcrtBare_exit(void)
{
	// platform_driver_unregister(&fcrtBare_driver);
	printk(KERN_INFO"FCRT Bare. Goodbye module world.\n");
}

module_init(fcrtBare_init);
module_exit(fcrtBare_exit);
